"""Subset the icofont icon font down to the glyphs this app actually uses.

The shipped font is 537KB (woff2) because it contains thousands of icons, but
the app only ever renders ~150 of them. Subsetting cuts the download to a few
KB, which is a large win for mobile first paint.

Reads:  public/css/icofont.min.css   (class -> codepoint map)
        app/ + components/           (which classes are actually used)
Writes: public/fonts/icofont-subset.woff2
        public/css/icofont-subset.css
"""
import os
import re
import glob

ROOT = r"C:\Users\Admin\Desktop\extremis\Frontend"
CSS_IN = os.path.join(ROOT, "public", "css", "icofont.min.css")
FONT_IN = os.path.join(ROOT, "public", "fonts", "icofont.woff2")
OUT_FONT = os.path.join(ROOT, "public", "fonts", "icofont-subset.woff2")
OUT_CSS = os.path.join(ROOT, "public", "css", "icofont-subset.css")

# --- 1. class name -> codepoint, from the shipped stylesheet -----------------
css = open(CSS_IN, encoding="utf-8", errors="ignore").read()
class_to_code = {}
for m in re.finditer(r'\.icofont-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', css):
    class_to_code[m.group(1)] = int(m.group(2), 16)
print(f"stylesheet defines {len(class_to_code)} icons")

# --- 2. which icons does the app actually reference? -------------------------
used = set()
for base in ("app", "components", "lib"):
    for path in glob.glob(os.path.join(ROOT, base, "**", "*.*"), recursive=True):
        if not path.endswith((".tsx", ".ts", ".jsx", ".js", ".css")):
            continue
        try:
            text = open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        for name in re.findall(r"icofont-([a-z0-9-]+)", text):
            used.add(name)

# `icofont-spin` / `icofont-pulse` are animation modifiers, not glyphs.
MODIFIERS = {"spin", "pulse", "fw", "lg", "2x", "3x", "4x", "5x", "rotate", "flip"}
used -= MODIFIERS

# Icons built from template literals resolve at runtime, so a static scan only
# sees the prefix (e.g. `icofont-caret-${...}` -> "caret-"). List every variant
# those expressions can produce so the glyphs survive subsetting.
DYNAMIC_VARIANTS = [
    "caret-down", "caret-right", "caret-up", "caret-left",
    "rounded-down", "rounded-right", "rounded-up", "rounded-left",
]
used |= set(DYNAMIC_VARIANTS)
used -= {"caret-", "rounded-"}

resolved = {n: class_to_code[n] for n in used if n in class_to_code}
missing = sorted(n for n in used if n not in class_to_code)
print(f"app references {len(used)} icofont classes; {len(resolved)} resolved to glyphs")
if missing:
    print("  unresolved (ignored):", ", ".join(missing[:12]), "..." if len(missing) > 12 else "")

codepoints = sorted(set(resolved.values()))
print(f"subsetting to {len(codepoints)} glyphs")

# --- 3. subset the font ------------------------------------------------------
from fontTools import subset  # noqa: E402

unicodes = ",".join(f"U+{cp:04X}" for cp in codepoints)
args = [
    FONT_IN,
    f"--unicodes={unicodes}",
    f"--output-file={OUT_FONT}",
    "--flavor=woff2",
    "--layout-features=",
    "--no-hinting",
    "--desubroutinize",
    "--drop-tables+=GSUB,GPOS,GDEF",
]
subset.main(args)

before = os.path.getsize(FONT_IN)
after = os.path.getsize(OUT_FONT)
print(f"font: {before/1024:.0f}KB -> {after/1024:.1f}KB  ({100 - after*100/before:.1f}% smaller)")

# --- 4. emit a stylesheet with only the used glyph rules --------------------
rules = []
for name in sorted(resolved):
    rules.append(f".icofont-{name}:before{{content:\"\\{resolved[name]:x}\"}}")

css_out = f"""/* Auto-generated by scripts/subset-icofont.py — do not edit by hand.
   Contains only the {len(resolved)} icofont glyphs this app actually uses,
   backed by a {after/1024:.1f}KB subset font instead of the {before/1024:.0f}KB original. */
@font-face {{
  font-family: 'IcoFont';
  src: url('/fonts/icofont-subset.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}}
[class^="icofont-"], [class*=" icofont-"] {{
  font-family: 'IcoFont' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}
{chr(10).join(rules)}
"""
open(OUT_CSS, "w", encoding="utf-8").write(css_out)
print(f"wrote {os.path.relpath(OUT_CSS, ROOT)} ({len(rules)} rules)")
